require:
  - rubocop-rspec
  - rubocop-performance

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Rails/HttpPositionalArguments:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
